### ISSUE TITLE
Higher upper limit on year encoding

### ISSUE THREAD

**Issue by leebickmtu** [wbolster/temporenc#3]
I would strongly urge you to include at least 2 more bits for the year storage to give a upper limit of 16383.

There are projects that exist for the archiving of digital material so that it won't be lost for future generations. It's not like in the past where physical object are able to be stored, in the digital age it is important that digital creations not only be stored but be stored in formats that are sustainable for hundreds or even thousands of years.

http://en.wikipedia.org/wiki/Digital_library#The_future

Please consider if you want this format to be something that can truly be standardized on for the long term future of increasing the year by 2 or more bits minimum. I mean how much does 2 bits really cost anyways.

**Comment by jodastephen** [comment]
JSR-310 has year limits at -1,000,000,000 to +1,000,000,000. It seems to me that any encoding spec should scale up to recording must bigger values than the 4095 years currently proposed.

**Comment by wbolster** [comment]
while this issue is not 'resolved', i will close it in favour of #4 which covers this topic (and other topics)
