### ISSUE TITLE
Terminology - time-zone

### ISSUE THREAD

**Issue by jodastephen** [wbolster/temporenc#5]
In JSR-310 (The Java 8 date and time library), we distinguish between "zone offset" and "time zone"

* zone offset - the number of hours, minutes and seconds from GMT, eg +02:00
* time zone - the rules defining how the offset changes over time, eg. Europe/Paris

Given that Temporenc uses offsets, not zones with rules, could the spec be changed to define and use the term "zone offset" to avoid confusion?

**Comment by wbolster** [comment]
agreed, good point
